AdvancedOptions: true
RuntimeType: Container
DockerFilePath: docker/run/Dockerfile
ServiceType: private
ArtifactSourceType: Dockerfile
ServiceBuildRegion: ap-southeast-1
RepoName: mengjunwei-mjw/agent-zero
RegionId: cn-hangzhou
CustomParameters: ''
DockerBuildArgs:
- ArgumentValue: main
  ArgumentName: BRANCH
Owner: mengjunwei-mjw
Branch: main
Platform: github
